project:
  type: website
  output-dir: public
  pre-render:
    - python _helper/cleanup.py
  preview:
    port: 8000

execute:
  freeze: auto

lightbox: true
bibliography: assets/bibliography.bib
biblio-title: References
csl: assets/apa-6th-edition.csl

filters:
  - _helper/git-version.lua

website:
  title: "_Drosophila_ Curriculum"
  site-url: https://floesche.github.io/drosophila-curriculum
  navbar:
    left:
      - text: "Protocols"
        href: protocols/index.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "Students"
        href: students/index.qmd
      - text: "Instructors"
        href: instructors/index.qmd
    right:
      - icon: github
        href: https://github.com/floesche/drosophila-curriculum
  sidebar:
  - title: "Protocols"
    collapse-level: 1
    contents:
      - text: Protocols
        href: protocols/index.qmd
      - text: "Identified Neurons, Identified behaviors, Mapped Circuits"
        href: protocols/catmaid01.qmd
      - text: "Exploring lineages in the larval VNC"
        href: protocols/catmaid02.qmd
      - text: "Intro to Optogenetics"
        href: protocols/optogenetics.qmd

      - section: "Developmental Logic as Circuit Blueprint"
        contents:
          - text: Student Version
            href: protocols/hemilineage_student.qmd
          - text: Instructor Version
            href: protocols/hemilineage.qmd

      - section: "Sensory Processing to Sequential Action Control"
        contents:
          - text: Student Version
            href: protocols/hierarchy_student.qmd
          - text: Instructor Version
            href: protocols/hierarchy_instructor.qmd

      - text: "Aggression"
        href: protocols/aggression.qmd
      - text: "Tracing a visual circuit"
        href: protocols/celltype-explorer.qmd
      - text: "Sleep"
        href: protocols/sleep.qmd
  page-footer:
    center: ""

format:
  html:
    theme: [yeti, assets/pbs.scss]
    toc: true
    code-fold: true
    link-external-icon: true
    link-external-newwindow: false
    embed-resources: false
    format-links:
      - format: typst
        text: PDF
        icon: file-pdf
      - docx
      - format: gfm
        text: Markdown (gfm)
        icon: markdown
  typst:
    section-numbering: "1.1.1.1"
    papersize: us-letter
    fontsize: 10pt
    margin:
      x: 1in
      y: 1in
    columns: 2
    template-partials:
      - _helper/typst-template.typ
      - _helper/typst-show.typ
      - _helper/biblio.typ
    filters:
      - _helper/detect-citations.lua
      - _helper/video-placeholder.lua
    include-before-body:
      - _helper/figure-span.typ
      - _helper/inline-code-wrap.typ
  docx: default
  gfm: default
